import React from 'react';
import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

const Terms: React.FC = () => {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-800 font-inter">
      <Helmet>
        <title>Terms of Service | Ikkish SaaS</title>
      </Helmet>
      
      <div className="max-w-4xl mx-auto px-6 py-12">
        <Link to="/" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-primary transition-colors mb-8">
          <ArrowLeft size={16} /> Back to Home
        </Link>
        
        <h1 className="text-4xl font-black mb-2 tracking-tight text-slate-900">Terms of Service</h1>
        <p className="text-slate-500 mb-12">Last Updated: July 2026</p>
        
        <div className="space-y-8 prose prose-slate max-w-none prose-headings:font-bold prose-headings:text-slate-900">
          
          <section>
            <h2 className="text-2xl mb-4 font-bold">1. Acceptance of Terms</h2>
            <p>
              By accessing and using the software, services, and AI generation tools ("PitchKing") provided by <strong>Ikkish SaaS</strong> ("Company", "we", "us", or "our"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl mb-4 font-bold">2. Age Restriction</h2>
            <p>
              To create an account and purchase Vault Credits on our platform, <strong>you must be at least 18 years of age</strong>. By purchasing Vault Credits, you represent and warrant that you meet this age requirement.
            </p>
          </section>

          <section>
            <h2 className="text-2xl mb-4 font-bold">3. Intellectual Property (IP) Ownership & Confidentiality</h2>
            <p>
              We understand that pitch decks contain highly confidential and proprietary startup ideas.
            </p>
            <p>
              <strong>You retain 100% full copyright and Intellectual Property (IP) ownership</strong> of all data you input into our platform and all final PDF documents/slide decks generated by PitchKing. Ikkish SaaS claims absolutely no ownership, licensing rights, or claims over your generated pitch decks, startup concepts, or business models. Your IP remains yours.
            </p>
          </section>

          <section>
            <h2 className="text-2xl mb-4 font-bold">4. Anti-Abuse and Fair Usage Policy (FUP)</h2>
            <p>
              Our AI infrastructure incurs hard costs. To ensure a stable experience for all users:
            </p>
            <p>
              <strong>Any attempt to reverse-engineer, use automated bots, scrape, or spam our generation endpoints will result in immediate account termination without a refund.</strong> You agree to use the service manually via the provided user interface for its intended purpose.
            </p>
          </section>

          <section>
            <h2 className="text-2xl mb-4 font-bold">5. AI-Generated Content Disclaimer</h2>
            <p>
              PitchKing utilizes third-party Large Language Models (LLMs) to expand your inputs into complete slides. You acknowledge that:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-4">
              <li>AI-generated content is provided "as is" and may contain hallucinations, inaccuracies, or fictitious data.</li>
              <li>You are solely responsible for reviewing, editing, and verifying the accuracy of all numbers, market sizes, and claims before using the pitch deck for actual fundraising or commercial purposes.</li>
              <li>Ikkish SaaS is not liable for any investment decisions, financial losses, or reputational damage resulting from the use of our AI-generated decks.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl mb-4 font-bold">6. Vault Credits</h2>
            <p>
              PitchKing operates on a Pay-As-You-Go model using "Vault Credits". Credits are consumed upon successful AI generation and PDF rendering. Vault Credits do not expire as long as your account remains active, but they are strictly non-transferable.
            </p>
          </section>

          <section>
            <h2 className="text-2xl mb-4 font-bold">7. Contact Information</h2>
            <p>
              If you have any questions about these Terms, please contact us at: <strong>ikkishprep@gmail.com</strong>
            </p>
            <p className="mt-2">
              <strong>Company Address:</strong><br />
              Plot no. 1502 ward no 12, Gautam Nagar<br />
              Chandauli, UTTAR PRADESH 232104, IN
            </p>
          </section>

        </div>
      </div>
    </div>
  );
};

export default Terms;
